version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"  # A porta ainda é mapeada para o load balancer agora
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: vitta1
      MYSQL_USER: admvitta
      MYSQL_PASSWORD: 123
    volumes:
      - dbdata:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8081:80"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Mapeia a configuração do NGINX
    ports:
      - "80:80"  # Porta de entrada para o load balancer
    depends_on:
      - web
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network: